SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, ROUND(precio * 1.05, 2) FROM producto;
SELECT nombre AS `product name`, precio AS `euros`, ROUND(precio * 1.05, 2) AS `dollars` FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, SUBSTRING(UPPER(nombre), 1, 2) AS code FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT f.codigo FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante;
SELECT DISTINCT(f.codigo) FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT nombre FROM fabricante LIMIT 5;
SELECT nombre FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre, f.codigo AS codigo_fabricante, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p, fabricante f ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p, fabricante f ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo';
SELECT p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Crucial' AND p.precio > 200;
SELECT p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND (f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate');
SELECT p.nombre FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, p.precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre LIKE '%e';
SELECT p.nombre, p.precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre LIKE '%w%';
SELECT p.nombre, p.precio, f.nombre AS fabricante FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT DISTINCT(f.codigo), f.nombre FROM fabricante f, producto p WHERE f.codigo = p.codigo_fabricante;
SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
SELECT p.nombre FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre = 'Lenovo';
SELECT DISTINCT(p.codigo), p.nombre, p.precio, p.codigo_fabricante FROM producto p, fabricante f WHERE p.precio = (SELECT MAX(p.precio) FROM producto p, fabricante f WHERE f.nombre = 'Lenovo');
SELECT p.nombre, p.precio FROM producto p, fabricante f WHERE f.nombre = 'Lenovo' AND p.precio = (SELECT MAX(p.precio) FROM producto p);
SELECT p.nombre, p.precio FROM producto p, fabricante f WHERE f.nombre = 'Hewlett-Packard' AND p.precio = (SELECT MIN(p.precio) FROM producto p);
SELECT DISTINCT(p.nombre), p.precio FROM producto p, fabricante f WHERE p.precio >= (SELECT MAX(p.precio) FROM producto p, fabricante f WHERE f.nombre = 'Lenovo');
SELECT p.nombre, p.precio FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Asus' AND p.precio > (SELECT AVG(p.precio) FROM producto p, fabricante f WHERE p.codigo_fabricante = f.codigo AND f.nombre = 'Asus');
